my_publisher:
  ros__parameters:
    test_count: 8 #测试，修改默认参数看是否能用外部yaml修改内部python参数
    publish_period: 0.3

my_subscriber:
  ros__parameters:
    balance_threshold: 5.0
    low_voltage_threshold: 11.0
    high_temp_threshold: 42.0